{ lib
, config
, ...
}:
let
  # This is taken from Home Manager's wofi.nix
  toConfig = attrs:
  ''
    # Generated by Home Manager.
  '' + lib.generators.toKeyValue { }
  (lib.filterAttrs (name: value: value != null) attrs);
 in {
  home-manager = lib.mkIf config.tw.programs.hyprland.enable {
    users.tim = {
      programs.wofi = {
        enable = true;
        settings = {
          width = 600;
          height = 300;
          location = "center";
          show = "drun";
          prompt = "Search...";
          filter_rate = 100;
          allow_markup = true;
          no_actions = true;
          halign = "fill";
          orientation = "vertical";
          content_haligh = "fill";
          insensitive = true;
          allow_images = true;
          image_size = 40;
          gtk_dark = true;
          dynamic_lines = true;
        };
        style = ''
window {
    margin: 0px;
    border: 5px solid #${config.tw.users.tim.colorScheme.palette.base01};
    background-color: #${config.tw.users.tim.colorScheme.palette.base00};
    border-radius: 0px;
}

#input {
    padding: 4px;
    margin: 4px;
    padding-left: 20px;
    border: none;
    color: #${config.tw.users.tim.colorScheme.palette.base05};
    font-weight: bold;
    background-color: #${config.tw.users.tim.colorScheme.palette.base01};
   	outline: none;
    border-radius: 15px;
    margin: 10px;
    margin-bottom: 2px;
}
#input:focus {
    border: 0px solid #${config.tw.users.tim.colorScheme.palette.base01};
    margin-bottom: 0px;
}

#inner-box {
    margin: 4px;
    border: 10px solid #${config.tw.users.tim.colorScheme.palette.base01};
    color: #${config.tw.users.tim.colorScheme.palette.base05};
    font-weight: bold;
    background-color: #${config.tw.users.tim.colorScheme.palette.base01};
    border-radius: 15px;
}

#outer-box {
    margin: 0px;
    border: none;
    border-radius: 15px;
    background-color: #${config.tw.users.tim.colorScheme.palette.base01};
}

#scroll {
    margin-top: 5px;
    border: none;
    border-radius: 15px;
    margin-bottom: 5px;
}

#img:selected {
    background-color: #${config.tw.users.tim.colorScheme.palette.base02};
    border-radius: 15px;
}

#text:selected {
    color: #${config.tw.users.tim.colorScheme.palette.base00};
    margin: 0px 0px;
    border: none;
    border-radius: 15px;
    background-color: #${config.tw.users.tim.colorScheme.palette.base02};
}

#entry {
    margin: 0px 0px;
    border: none;
    border-radius: 15px;
    background-color: transparent;
}

#entry:selected {
    margin: 0px 0px;
    border: none;
    border-radius: 15px;
    background-color: #${config.tw.users.tim.colorScheme.palette.base02};
}
        '';
      };

      xdg.configFile."wofi/config-bmenu".text = toConfig {
        width = 375;
        height = 450;
        location = "top_left";
        show = "drun";
        prompt = "Search...";
        filter_rate = 100;
        allow_markup = true;
        no_actions = false;
        halign = "fill";
        orientation = "vertical";
        content_halign = "fill";
        insensitive = true;
        allow_images = true;
        image_size = 32;
        gtk_dark = true;
        layer = "top";
      };
    };
  };
}
